# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 赵昉宇
email: zhaofnagyu16@gmail.com
description: 博观而取约，厚积而薄发
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhaofangyu.github.io/" # http://yourdomain.com  -the base hostname & protocol for your site
twitter_username: zhaofangyu
email:  zhaofangyu16@gmail.com
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
